version: '3'
services:
  apache:
    image: httpd
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options: 
        awslogs-group: tutorial-apache
        awslogs-region: us-east-2
        awslogs-stream-prefix: apache
